
//控件//
#define IDOK 1
#define IDCANCEL 2
#define IDSTART 4000
#define IDEND 4001
#define IDC_MY_IMAGE_ONE 1000
#define IDC_CUSTOM_TEXT 1001
#define IDC_CUSTOM_TEXT_TWO 1002
#define IDC_INFORMATION 1003
#define IDC_PHOTO 1004
#define IDC_MONITOR 1005
#define IDC_USERS 1006
#define IDC_BROADCAST_INFORAMATION 1007
#define IDC_BROADCAST_INFORAMATION_EDIT 1008

//对话框//
#define IDD_MYDIALOG_ONE 3001//开始框//
#define IDD_MYDIALOG_END 3002//结束框//
#define IDD_MYDIALOG_INFORMATION 3003//消息框//
#define IDD_MYDIALOG_PHOTO 3004 //头像显示框//
#define IDD_MYDIALOG_MONITOR 3005//监控框//
#define IDD_MYDIALOG_BROADCAST 3006 //广播框//
#define IDD_MYDIALOG_BROADCAST_INFORMATION 3007 //广播消息输入框//
//自定义消息类型//
#define WM_APP_UPDATE_MSG (WM_APP+1)
#define WM_APP_UPDATEPHOTO_MSG (WM_APP+2)
#define WM_APP_UPDATEMONITOR_MSG (WM_APP+3)
#define WM_APP_UPDATEBROADCAST_MSG (WM_APP+4)

//标识符//
#define LBS_SINGLESEL 10000
